# https://github.com/chanzuckerberg/napari-hub/wiki/A-plugin-developerâ€™s-guide-to-categories-on-the-napari-hub
# https://bioportal.bioontology.org/ontologies/EDAM-BIOIMAGING/?p=classes&conceptid=root
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - Medical imaging
  - Microscopy
  - 2D image
  - 3D image
  - Image time series
  - Multi-channel image
  - Object detection
  - Cell segmentation
  - Model-based segmentation
  - Convolutional neural network
  - Supervised learning
